Repository KNU-Finnect/Finnect_frontend, pull requests merged in 2024-05, with the labels that each got.

#3 Feat/2 routerset
  .pnp.cjs
  package.json
  src/App.tsx
  src/main.tsx
  src/pages/ErrorPage.tsx
  src/pages/RootPage.tsx
  yarn.lock
Labels: ✨ Feature, 📦 Environment

#8 header 및 버거 메뉴 클릭했을때 초대 모달창 구현
  .pnp.cjs
  index.html
  package.json
  src/App.tsx
  src/atoms/.gitkeep
  src/atoms/header/useHeaderMenu.ts
  src/atoms/header/useInviteModal.ts
  src/atoms/sider/useSelectedMenu.ts
  src/components/common/header/HeaderBox.tsx
  src/components/common/header/HeaderPath.tsx
  src/components/common/header/HeaderSubMenu.tsx
  src/components/common/modal/InviteModal.tsx
  src/components/common/sider/Records.tsx
  src/components/common/sider/SiderBox.tsx
  src/components/common/sider/Views.tsx
  src/components/common/sider/WorkSpace.tsx
  src/components/common/slider/Records.tsx
  src/pages/RootPage.tsx
  src/pages/workspace/WorkSpacePage.tsx
  src/styles/Theme.ts
  yarn.lock
Labels: ✨ Feature, 💄 Design

#10 회사 더미데이터 및 와이어프레임 구현
  .pnp.cjs
  package.json
  src/components/common/.gitkeep
  src/components/common/header/HeaderSubMenu.tsx
  src/components/common/modal/company/ColumnForm.tsx
  src/components/common/modal/company/CompanyForm.tsx
  src/components/common/modal/header/InviteModal.tsx
  src/components/common/sider/WorkSpace.tsx
  src/interface/CompanyInterface.ts
  src/main.tsx
  src/pages/companies/CompaniesBox.tsx
  src/pages/companies/components/CompanyAgGrid.tsx
  src/pages/deals/DealsBox.tsx
  src/pages/peoples/PeoplesBox.tsx
  src/pages/workspace/WorkSpacePage.tsx
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: ✨ Feature, 💄 Design

#12 Feat/1 login
  src/App.tsx
  src/components/signin/IDbox.tsx
  src/components/signin/PWbox.tsx
  src/pages/SigninPage.tsx
Labels: ✨ Feature, 💄 Design

#15 Feat/13 signup
  .pnp.cjs
  .yarn/sdks/typescript/package.json
  src/App.tsx
  src/components/.gitkeep
  src/components/login/IDCheckbox.tsx
  src/components/login/IDbox.tsx
  src/components/login/Namebox.tsx
  src/components/login/PWCheckbox.tsx
  src/components/login/PWbox.tsx
  src/components/signin/PWbox.tsx
  src/pages/login/SigninPage.tsx
  src/pages/login/SignupPage.tsx
Labels: ✨ Feature, 💄 Design

#21 Yarn Berry -> Pnpm 마이그레이션
  .eslintrc.cjs
  .eslintrc.json
  .gitignore
  .pnp.cjs
  .pnp.loader.mjs
  .prettierrc
  .prettierrc.cjs
  .vscode/extensions.json
  .yarn/releases/yarn-4.1.1.cjs
  .yarn/sdks/eslint/bin/eslint.js
  .yarn/sdks/eslint/lib/api.js
  .yarn/sdks/eslint/lib/unsupported-api.js
  .yarn/sdks/eslint/package.json
  .yarn/sdks/integrations.yml
  .yarn/sdks/prettier/bin/prettier.cjs
  .yarn/sdks/prettier/index.cjs
  .yarn/sdks/prettier/package.json
  .yarn/sdks/typescript/bin/tsc
  .yarn/sdks/typescript/bin/tsserver
  .yarn/sdks/typescript/lib/tsc.js
  .yarn/sdks/typescript/lib/tsserver.js
  .yarn/sdks/typescript/lib/tsserverlibrary.js
  .yarn/sdks/typescript/lib/typescript.js
  .yarn/sdks/typescript/package.json
  .yarnrc.yml
  eslint.config.js
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/main.tsx
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: 🐛 BugFix, 📦 Environment, 🚑 !HOTFIX

#25 Deploy/22 cicd
  .github/workflows/main.yml
Labels: 🚀 Deploy

#29 해당 워크 스페이스 생성 및 데이터 가져오기 구현, 회사 데이터 가져오기 구현
  .eslintrc.cjs
  .gitignore
  .prettierrc
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/apis/.gitkeep
  src/apis/API_JWT.ts
  src/apis/workspace/useGetWorkSpace.ts
  src/apis/workspace/usePostWorkSpace.ts
  src/atoms/company/useCompany.ts
  src/atoms/header/useHeaderMenu.ts
  src/components/common/sider/WorkSpace.tsx
  src/constants/.gitkeep
  src/constants/URI.ts
  src/hooks/.gitkeep
  src/hooks/custom-hooks/.gitkeep
  src/hooks/custom-hooks/useCompanyData.ts
  src/hooks/custom-hooks/useCompanyModal.ts
  src/hooks/queries/.gitkeep
  src/hooks/queries/Http.ts
  src/hooks/queries/workspace/useGetWorkSpaceQuery.ts
  src/hooks/queries/workspace/usePostWorkSpaceQuery.ts
  src/interface/CompanyInterface.ts
  src/interface/WorkspaceInterface.ts
  src/main.tsx
  src/mocks/Browser.ts
  src/mocks/handler/Handler.ts
  src/mocks/handler/company/CompanyHandler.ts
  src/pages/companies/CompaniesBox.tsx
  src/pages/companies/components/CompanyAgGrid.tsx
  src/pages/companies/components/CompanyCategories.tsx
Labels: ✨ Feature, 💄 Design, 👽 API
